name: ci

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
    paths:
      - 'docker-bake.hcl'
      - 'Dockerfile'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: chocolatefrappe/nginx-s3-gateway
          tags: type=raw,value=latest

      - name: Build
        uses: docker/bake-action@v3
        with:
          files: |
            ./docker-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
          push: ${{ github.event_name != 'pull_request' }}

      - name: Docker Metadata Summary
        uses: dockerbakery/docker-metadata-summary@v1
